//  The resolved configuration the CLI hands to the runtime.
//
//  `cider run` reads and validates Cider.yaml, then writes a launch descriptor
//  and starts the application with it. The runtime never parses YAML.
//
//  Two reasons for the split. Validation is the toolchain's job and produces
//  file-and-line diagnostics that the runtime has no business reproducing. And
//  the descriptor is a versioned wire format between two programs, so it can
//  stay boring and line-oriented while the manifest schema evolves.
//
//  The format is deliberately trivial -- `key = value`, one per line, `#` for
//  comments -- so that a developer can read one in a crash report and so the
//  parser has no interesting failure modes.

/// A capability the manifest granted the application.
public struct AppPermissions: Equatable, Sendable {
    public var network: Bool
    public var localStorage: Bool

    public init(network: Bool, localStorage: Bool) {
        self.network = network
        self.localStorage = localStorage
    }

    public static let none = AppPermissions(network: false, localStorage: false)
}

public struct LaunchDescriptor: Equatable, Sendable {
    /// Bumped whenever a field's meaning changes. A runtime refuses a descriptor
    /// it does not understand rather than guessing.
    public static let currentVersion = 1

    public var version: Int
    public var appID: String
    public var appName: String
    public var appEntry: String
    public var minimumCompatibility: String
    public var deviceProfileName: String
    public var permissions: AppPermissions
    public var logLevel: LogLevel
    public var inspectorEnabled: Bool

    /// Where the runtime writes the latest structured inspector snapshot when inspection is enabled.
    public var inspectorSnapshotPath: String

    /// Local dev-mode proxy endpoint for capturing CiderHTTP requests. Empty means direct requests.
    public var requestCaptureProxyURL: String

    /// Root of this application's isolated on-disk data area, prepared by
    /// `cider run` before launch (docs/03-technical-architecture.md section
    /// 8: "per-app data roots"). Empty when the binary was started without
    /// going through the CLI, in which case no sandbox root exists.
    public var sandboxDataRoot: String

    public init(
        version: Int = LaunchDescriptor.currentVersion,
        appID: String,
        appName: String,
        appEntry: String,
        minimumCompatibility: String,
        deviceProfileName: String,
        permissions: AppPermissions,
        logLevel: LogLevel = .info,
        inspectorEnabled: Bool = false,
        sandboxDataRoot: String = "",
        inspectorSnapshotPath: String = "",
        requestCaptureProxyURL: String = ""
    ) {
        self.version = version
        self.appID = appID
        self.appName = appName
        self.appEntry = appEntry
        self.minimumCompatibility = minimumCompatibility
        self.deviceProfileName = deviceProfileName
        self.permissions = permissions
        self.logLevel = logLevel
        self.inspectorEnabled = inspectorEnabled
        self.sandboxDataRoot = sandboxDataRoot
        self.inspectorSnapshotPath = inspectorSnapshotPath
        self.requestCaptureProxyURL = requestCaptureProxyURL
    }

    public func encoded() -> String {
        """
        # Generated by cider. Edits are overwritten on the next run.
        descriptor-version = \(version)
        app.id = \(appID)
        app.name = \(appName)
        app.entry = \(appEntry)
        runtime.minimum-compatibility = \(minimumCompatibility)
        device.name = \(deviceProfileName)
        permissions.network = \(permissions.network)
        permissions.local-storage = \(permissions.localStorage)
        log.level = \(logLevel.name)
        inspector.enabled = \(inspectorEnabled)
        sandbox.data-root = \(sandboxDataRoot)
        inspector.snapshot-path = \(inspectorSnapshotPath)
        request-capture.proxy-url = \(requestCaptureProxyURL)

        """
    }

    public static func decode(_ text: String) throws -> LaunchDescriptor {
        var fields: [String: String] = [:]

        for (index, rawLine) in text.split(separator: "\n", omittingEmptySubsequences: false).enumerated() {
            let line = rawLine.trimmingASCIIWhitespace()
            if line.isEmpty || line.hasPrefix("#") { continue }

            guard let separator = line.firstIndex(of: "=") else {
                throw Diagnostic(
                    code: "CID0301",
                    summary: "malformed launch descriptor",
                    location: DiagnosticLocation(file: "<launch descriptor>", line: index + 1),
                    reason: "Line \(index + 1) is not a `key = value` pair: \(line)",
                    remedy: "Delete the descriptor and re-run `cider run` to regenerate it."
                )
            }

            let key = String(line[line.startIndex..<separator]).trimmingASCIIWhitespace()
            let value = String(line[line.index(after: separator)...]).trimmingASCIIWhitespace()
            fields[key] = value
        }

        func required(_ key: String) throws -> String {
            guard let value = fields[key], !value.isEmpty else {
                throw Diagnostic(
                    code: "CID0302",
                    summary: "launch descriptor is missing '\(key)'",
                    reason: "The runtime needs \(key) to start an application.",
                    remedy: "Re-run `cider run` to regenerate the descriptor."
                )
            }
            return value
        }

        let version = Int(try required("descriptor-version")) ?? 0
        guard version == currentVersion else {
            throw Diagnostic(
                code: "CID0303",
                summary: "unsupported launch descriptor version \(version)",
                reason: """
                    This Cider runtime understands descriptor version \(currentVersion). \
                    The descriptor was written by a different version of the toolchain.
                    """,
                remedy: "Rebuild with a matching `cider` and runtime, then run again."
            )
        }

        return LaunchDescriptor(
            version: version,
            appID: try required("app.id"),
            appName: try required("app.name"),
            appEntry: try required("app.entry"),
            minimumCompatibility: try required("runtime.minimum-compatibility"),
            deviceProfileName: try required("device.name"),
            permissions: AppPermissions(
                network: fields["permissions.network"] == "true",
                localStorage: fields["permissions.local-storage"] == "true"
            ),
            logLevel: fields["log.level"].flatMap(LogLevel.init(name:)) ?? .info,
            inspectorEnabled: fields["inspector.enabled"] == "true",
            sandboxDataRoot: fields["sandbox.data-root"] ?? "",
            inspectorSnapshotPath: fields["inspector.snapshot-path"] ?? "",
            requestCaptureProxyURL: fields["request-capture.proxy-url"] ?? ""
        )
    }
}
